
default: &default
  adapter: pg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: elastic_development

test:
  <<: *default
  database: elastic_test

production:
  <<: *default
  database: elastic_production
